title: 30 Days Of Python — by Mark Anthony Ribaldo (RibaldzZ)
description: A 30-day Python programming challenge adapted for Filipino students. Daily exercises, projects, and real-world examples.
markdown: kramdown
theme: jekyll-theme-cayman
